[build-system]
requires = ['setuptools']
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ['riveter']

[project]
name = 'riveter'
version = '0.00.01'
readme = {file = "README.md", content-type = "text/markdown"}
authors = [{name = "Maria Antoniak", email = "mariaa@allenai.org"}]
description = 'A toolkit for using verb lexicons like connotation frames'
license = 'GPL-3.0-only'
requires-python = ">=3.8"
classifiers=[
  "Programming Language :: Python :: 3",
  "Operating System :: OS Independent",
]
dependencies = [
  'numpy==1.24.1',
  'spacy', 
  'seaborn',
  'spacy-experimental',
  'en-coreference-web-trf @ https://github.com/explosion/spacy-experimental/releases/download/v0.6.0/en_coreference_web_trf-3.4.0a0-py3-none-any.whl#egg=en_coreference_web_trf',
]

[project.urls]
Homepage = 'https://github.com/maartensap/riveter-nlp'
